---
title: "Sleep hygiene Post-Survey 5/9/2021"
output:
  html_document:
    code_folding: hide
    theme: flatly
    highlight: tango
  pdf_document: default
  word_document: default
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 20, fig.height = 20, results="asis")
```

```{r Load up packages to use}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(arsenal)
library(data.table)
library(expss)
```

```{r Read in data}
sleephygiene <- read_csv("/Users/Ivanics/Desktop/SPH/4th term/HealthComm/Qualtrics post/Sleep Hygiene Post-Survey_May 9, 2021_19.51.csv")

sleephygiene$StartDate <- lubridate::ymd_hms(sleephygiene$StartDate)

#Filter to include only responses beyond this time
sleephygiene <- sleephygiene %>% filter(StartDate >= "2021-04-29 00:00:00")

#Select out the variables we need
sleephygiene <- sleephygiene %>% select(Progress, `Duration (in seconds)`, Finished, LocationLatitude, LocationLongitude, DistributionChannel, UserLanguage, Q1, Q2, Q3, Q2_5_TEXT, Q4, Q5, Q6, Q37, Q92, Q93, Q94,  Q38, Q39, Q10_2, Q10_3, Q9, Q61, Q84, Q85, Q81, Q63, Q96_1, Q96_2, Q96_3, Q96_4, Q96_5, Q96_6, Q96_7, Q96_8, Q95, Q83, Q82, Q69, Q62, Q64, Q90, Q91, Q89_1, Q67_1, Q67_2, Q67_3, Q75_1, Q75_2, Q75_3, Q68, Q70, Q70_18_TEXT, Q87, Q71, Q72, Q79, Q79_5_TEXT, Q74, Q73, Q73_5_TEXT, Q59_1, Q59_2, Q59_3, Q59_4, Q44_1, Q44_2, Q44_3, Q44_4, Q44_5, Q44_6, Q44_7, Q44_8, Q44_9, Q52)

sleephygiene <- rowid_to_column(sleephygiene, "ID")
```

```{r Recoding factors}
#General factor recoding
sleephygiene <- sleephygiene %>% mutate(
  Q1_consent = factor(Q1)) %>%
  mutate(Q2_program = factor(Q2)) %>%
  mutate(Q3_role = factor(Q3)) %>%
  mutate(Q4_gender = factor(Q4)) %>%
  mutate(Q5_age = factor(Q5)) %>%
  mutate(Q6_numberinhousehold = as.numeric(Q6)) %>%
  mutate(Q37_employed = factor(Q37)) %>%
  mutate(Q92_notSPHemployed = factor(Q92)) %>%
  mutate(Q93_worksetting = factor(Q93)) %>%
  mutate(Q94_dayornight = factor(Q94)) %>%
  mutate(Q38_worksetting = factor(Q38)) %>%
  mutate(Q39_dayornight = factor(Q39)) %>%
  mutate(Q10_hoursofsleeplast5workdays = as.numeric(Q10_2)) %>%
  mutate(Q10_hoursofsleeppastweekend = as.numeric(Q10_3)) %>%
  mutate(Q9_howoftensleepypastmonth = factor(Q9)) %>%
  mutate(Q61_howoftensleepypasttwoweeks = factor(Q61)) %>%
  mutate(Q84_awareofhowtoimprovesleepquality = factor(Q84)) %>%
  mutate(Q81_seenorheardfromGNbloombergcampaign = factor(Q81)) %>%
  mutate(Q63_recalltoolsfreetect = factor(Q63)) %>%
  mutate(Q96_picture1 = factor(Q96_1)) %>%
  mutate(Q96_picture2 = factor(Q96_2)) %>%
  mutate(Q96_picture3 = factor(Q96_3)) %>%
  mutate(Q96_picture4 = factor(Q96_4)) %>%
  mutate(Q96_picture5 = factor(Q96_5)) %>%
  mutate(Q96_picture6 = factor(Q96_6)) %>%
  mutate(Q96_picture7 = factor(Q96_7)) %>%
  mutate(Q96_picture8 = factor(Q96_8)) %>%
  mutate(Q95_talkedtoanyone = factor(Q95)) %>%
  mutate(Q82_knowanyonewhoengaged = factor(Q82)) %>%
  mutate(Q69_didyouengagewiththecampaign = factor(Q69)) %>%
  mutate(Q90_areyouhappywithyoursleepquality_awareofcampaign = factor(Q90)) %>%
  mutate(Q91_areyouhappywithyoursleepquality_notawareofcampaign = factor(Q91)) %>%
  mutate(Q89_ratesleepquality_notawareofcampaign = factor(Q89_1)) %>%
  mutate(Q67_move30minutes = as.numeric(Q67_1)) %>%
  mutate(Q67_breathing = as.numeric(Q67_2)) %>%
  mutate(Q67_powerdown = as.numeric(Q67_2)) %>%
  mutate(Q75_moving = factor(Q75_1)) %>%
  mutate(Q75_breathing = factor(Q75_2)) %>%
  mutate(Q75_powerdown = factor(Q75_3)) %>%
  mutate(Q68_timing = factor(Q68)) %>%
  mutate(Q87_idealtime = factor(Q87)) %>%
  mutate(Q74_rafflemotivating = factor(Q74)) %>%
  mutate(Q75_moving = factor(Q75_1)) %>%
  mutate(Q59_canmaintainhealthysleephabits = factor(Q59_1)) %>%
  mutate(Q59_cancutoutscreen = factor(Q59_2)) %>%
  mutate(Q59_canexercise = factor(Q59_3)) %>%
  mutate(Q59_canparticipateinbreathing = factor(Q59_4)) %>%
  mutate(Q44_goodnightsleepisimportant = factor(Q44_1)) %>%
  mutate(Q44_mentalclarity = factor(Q44_2)) %>%
  mutate(Q44_feelpositive = factor(Q44_3)) %>%
  mutate(Q44_cuttingoutscreenleadstobettersleep = factor(Q44_4)) %>%
  mutate(Q44_exercisingleadstobettersleep = factor(Q44_5)) %>%
  mutate(Q44_breathingexercisesleadstobettersleep = factor(Q44_6)) %>%
  mutate(Q44_iwillstopscreens = factor(Q44_7)) %>%
  mutate(Q44_iwillexercise = factor(Q44_8)) %>%
  mutate(Q44_iwillbreathe = factor(Q44_9)) %>%
  mutate(Q52_additionalcomments = factor(Q52))

  
```

```{r Listvariables to binary}
#Q85
resp.split_85 <- strsplit(sleephygiene$Q85, ",")
lev <- unique(unlist(resp.split_85))
sleephygiene<- with(sleephygiene, data.frame(sleephygiene, t(sapply(resp.split_85, function(x) table(factor(x, levels=lev))))))

sleephygiene <- sleephygiene %>%
    mutate(Q85_waystoimprovesleepquality = case_when(
    Not.drinking.caffeinated.beverages.late.in.the.day == 1 ~ "Not drinking caffeinated beverages late in the day",
    Switching.off.electronics.one.hour.before.sleep == 1 ~ "Switching off electronics one hour before sleep",
    Incorporating.moderate.exercise.as.part.of.your.day == 1 ~ "Incorporating moderate exercise as part of your day",
    Increase.natural.bright.light.exposure.in.the.day == 1 ~ "Increase natural bright light exposure in the day",
    Reduce.irregular.or.long.daytime.naps == 1 ~ "Reduce irregular or long daytime naps",
    Try.to.sleep.and.wake.at.consistent.times == 1 ~ "Try to sleep and wake at consistent times",
    Take.a.melatonin.supplement == 1 ~ "Take a melatonin supplement",
    Decrease.alcohol.consumption == 1 ~ "Decrease alcohol consumption",
    Deep.breathing.exercises == 1 ~ "Deep breathing exercises"))

#Q83
resp.split_83 <- strsplit(sleephygiene$Q83, ",")
lev <- unique(unlist(resp.split_83))
sleephygiene<- with(sleephygiene, data.frame(sleephygiene, t(sapply(resp.split_83, function(x) table(factor(x, levels=lev))))))

sleephygiene <- sleephygiene %>%
    mutate(Q83_talkedtowho = case_when(
    Friends == 1 ~ "Friends",
    Spouse == 1 ~ "Spouse",
    Relatives == 1 ~ "Relatives",
    Colleague == 1 ~ "Colleague"))

#Q62
resp.split_62 <- strsplit(sleephygiene$Q62, ",")
lev <- unique(unlist(resp.split_62))
sleephygiene<- with(sleephygiene, data.frame(sleephygiene, t(sapply(resp.split_62, function(x) table(factor(x, levels=lev))))))

sleephygiene <- sleephygiene %>%
    mutate(Q62_howdidyouengage = case_when(
    Instagram.campaign == 1 ~ "Instagram campaign",
    Text.message.campaign == 1 ~ "Text message campaign",
    Word.of.mouth.discussion.with.others == 1 ~ "Word of mouth/discussion with others"))

#64
resp.split_64 <- strsplit(sleephygiene$Q64, ",")
lev <- unique(unlist(resp.split_64))
sleephygiene<- with(sleephygiene, data.frame(sleephygiene, t(sapply(resp.split_64, function(x) table(factor(x, levels=lev))))))

sleephygiene <- sleephygiene %>%
    mutate(Q64_whichtechniquedidyoutry = case_when(
    X.MoveMore == 1 ~ "Movemore",
    X.Breathe== 1 ~ "Breathe",
    X.PowerDown == 1 ~ "Powerdown",
    None.of.the.above == 1 ~ "None of the above"))

#70
resp.split_70 <- strsplit(sleephygiene$Q70, ",")
lev <- unique(unlist(resp.split_70))
sleephygiene<- with(sleephygiene, data.frame(sleephygiene, t(sapply(resp.split_70, function(x) table(factor(x, levels=lev))))))

sleephygiene <- sleephygiene %>%
    mutate(Q70_timingoftextsinconvenient = case_when(
    #Messages.were.too.frequent == 1 ~ "Messages were too frequent",
    Messages.were.too.infrequent== 1 ~ "Messages were too infrequent",
    Received.message.too.early.in.the.day == 1 ~ "Received message too early in the day",
    #Received.message.too.late.in.the.day == 1 ~ "Received message too late in the day",
    Other..please.explain.below. == 1 ~ "Other (please explain below)"))

#71
resp.split_71 <- strsplit(sleephygiene$Q71, ",")
lev <- unique(unlist(resp.split_71))
sleephygiene<- with(sleephygiene, data.frame(sleephygiene, t(sapply(resp.split_71, function(x) table(factor(x, levels=lev))))))

sleephygiene <- sleephygiene %>%
    mutate(Q71_whichchannelmosteducational = case_when(
    Text == 1 ~ "Text",
    Instagram == 1 ~ "Instagram"))
    #Discussion.with.others.about.the.campaign == 1 ~ "Discussion with others about the campaign",
    #None.of.the.above.1 == 1 ~ "None of the above"))

#72 - look into


#Q79
resp.split_79 <- strsplit(sleephygiene$Q79, ",")
lev <- unique(unlist(resp.split_79))
sleephygiene<- with(sleephygiene, data.frame(sleephygiene, t(sapply(resp.split_79, function(x) table(factor(x, levels=lev))))))

sleephygiene <- sleephygiene %>%
    mutate(Q79_moresuccessfuloutcomsuggestions = case_when(
    There.was.an.in.person.on.campus.component.to.the.campaign == 1 ~ "There was an in-person/on-campus component to the campaign",
    The.campaign.was.longer == 1 ~ "The campaign was longer",
    I.had.more.flexibility.in.my.day == 1 ~ "I had more flexibility in my day",
    There.were.subject.matter.experts.checking.in.with.me.one.on.one == 1 ~ "There were subject matter experts checking in with me one-on-one"))
    #Other == 1 ~ "Reduce irregular or long daytime naps",

#Q73
resp.split_73 <- strsplit(sleephygiene$Q73, ",")
lev <- unique(unlist(resp.split_73))
sleephygiene<- with(sleephygiene, data.frame(sleephygiene, t(sapply(resp.split_73, function(x) table(factor(x, levels=lev))))))

sleephygiene <- sleephygiene %>%
    mutate(Q73_hearabouthow = case_when(
    Instagram.1 == 1 ~ "Instagram",
    JHSPH.Activities.email == 1 ~ "JHSPH Activities email",
    #Class.announcement == 1 ~ "Class announcement",
    Word.of.mouth.discussion.with.others.1 == 1 ~ "Word of mouth/discussion with others"))
    #Other == 1 ~ "Reduce irregular or long daytime naps",
```

**Plots for wakeup and sleep times**
```{r fig.width = 12, fig.height = 12}
library(plotly)
workdayssleep <- sleephygiene %>% ggplot( aes(x=Q10_hoursofsleeplast5workdays)) +
    geom_histogram( binwidth=1, fill="#69b3a2", color="#e9ecef", alpha=0.9) +
    ggtitle("Hours of sleep last five workdays") +
  theme(
      text = element_text(size=30)
    ) +
  #theme_test(text = element_text(size=40)) + 
  labs(x="Number of hours of sleep in the past five workdays", y="Number of participants") +
  scale_x_continuous(expand = c(0, 0)) + scale_y_continuous(expand = c(0, 0), limits = c(0,65))
#workdayssleep
ggplotly(workdayssleep)

#Plot for weekend
weekend <- sleephygiene %>% ggplot( aes(x=Q10_hoursofsleeppastweekend)) +
    geom_histogram( binwidth=1, fill="#69b3a2", color="#e9ecef", alpha=0.9) +
    ggtitle("Hours of sleep last weekend") +
    theme(
      text = element_text(size=30)
    ) +
  labs(x="Number of hours of sleep in the past weekend", y="Number of participants") +
  scale_x_continuous(expand = c(0, 0)) + scale_y_continuous(expand = c(0, 0), limits = c(0,60))
#weekend
ggplotly(weekend)
```

```{r Applying labels}
#Tab 1
sleephygiene$Q9_howoftensleepypastmonth <- factor(sleephygiene$Q9_howoftensleepypastmonth, levels = c("Never", "Rarely", "Sometimes", "Very often", "Always"))
sleephygiene$Q61_howoftensleepypasttwoweeks <- factor(sleephygiene$Q61_howoftensleepypasttwoweeks, levels = c("Never", "Rarely", "Sometimes", "Very often", "Always"))
sleephygiene$Q89_ratesleepquality_notawareofcampaign <- factor(sleephygiene$Q89_ratesleepquality_notawareofcampaign, levels = c("Poor", "Fair", "Good", "Excellent"))
sleephygiene$Q75_moving <- factor(sleephygiene$Q75_moving, levels = c("Extremely unhelpful", "Somewhat unhelpful", "Neither helpful nor unhelpful", "Somewhat helpful", "Extremely helpful"))
sleephygiene$Q75_breathing <- factor(sleephygiene$Q75_breathing, levels = c("Extremely unhelpful", "Somewhat unhelpful", "Neither helpful nor unhelpful", "Somewhat helpful", "Extremely helpful"))
sleephygiene$Q75_powerdown <- factor(sleephygiene$Q75_powerdown, levels = c("Extremely unhelpful", "Somewhat unhelpful", "Neither helpful nor unhelpful", "Somewhat helpful", "Extremely helpful"))
sleephygiene$Q87_idealtime <- factor(sleephygiene$Q87_idealtime, levels = c("Early morning (6:00 am - 9:00 am)", "Late morning (9:01 am - 12:00 pm)", "Early afternoon (12:01 pm - 3:00 pm)", "Late afternoon (3:01 pm - 6:00 pm)", "Early evening (6:01 pm - 9:00 pm)", "Late evening (9:01 pm - 12:00 am)", "Other (please specify)"))
sleephygiene$Q59_canmaintainhealthysleephabits <- factor(sleephygiene$Q59_canmaintainhealthysleephabits, levels = c("Not at all confident", "Somewhat confident", "Extremely confident"))
sleephygiene$Q59_cancutoutscreen <- factor(sleephygiene$Q59_cancutoutscreen, levels = c("Not at all confident", "Somewhat confident", "Extremely confident"))
sleephygiene$Q59_canexercise <- factor(sleephygiene$Q59_canexercise, levels = c("Not at all confident", "Somewhat confident", "Extremely confident"))
sleephygiene$Q59_canparticipateinbreathing <- factor(sleephygiene$Q59_canparticipateinbreathing, levels = c("Not at all confident", "Somewhat confident", "Extremely confident"))
sleephygiene$Q44_goodnightsleepisimportant <- factor(sleephygiene$Q44_goodnightsleepisimportant, levels = c("Strongly disagree", "Somewhat disagree", "Neither agree nor disagree", "Somewhat agree", "Strongly agree"))
sleephygiene$Q44_mentalclarity <- factor(sleephygiene$Q44_mentalclarity, levels = c("Strongly disagree", "Somewhat disagree", "Neither agree nor disagree", "Somewhat agree", "Strongly agree"))
sleephygiene$Q44_feelpositive <- factor(sleephygiene$Q44_feelpositive, levels = c("Strongly disagree", "Somewhat disagree", "Neither agree nor disagree", "Somewhat agree", "Strongly agree"))
sleephygiene$Q44_cuttingoutscreenleadstobettersleep <- factor(sleephygiene$Q44_cuttingoutscreenleadstobettersleep, levels = c("Strongly disagree", "Somewhat disagree", "Neither agree nor disagree", "Somewhat agree", "Strongly agree"))
sleephygiene$Q44_exercisingleadstobettersleep <- factor(sleephygiene$Q44_exercisingleadstobettersleep, levels = c("Strongly disagree", "Somewhat disagree", "Neither agree nor disagree", "Somewhat agree", "Strongly agree"))
sleephygiene$Q44_breathingexercisesleadstobettersleep <- factor(sleephygiene$Q44_breathingexercisesleadstobettersleep, levels = c("Strongly disagree", "Somewhat disagree", "Neither agree nor disagree", "Somewhat agree", "Strongly agree"))
sleephygiene$Q44_iwillstopscreens <- factor(sleephygiene$Q44_iwillstopscreens, levels = c("Strongly disagree", "Somewhat disagree", "Neither agree nor disagree", "Somewhat agree", "Strongly agree"))
sleephygiene$Q44_iwillexercise <- factor(sleephygiene$Q44_iwillexercise, levels = c("Strongly disagree", "Somewhat disagree", "Neither agree nor disagree", "Somewhat agree", "Strongly agree"))
sleephygiene$Q44_iwillbreathe <- factor(sleephygiene$Q44_iwillbreathe, levels = c("Strongly disagree", "Somewhat disagree", "Neither agree nor disagree", "Somewhat agree", "Strongly agree"))

library(expss)
sleephygiene = apply_labels(sleephygiene,
                      Q3_role = "What is your role at Bloomberg",
                      Q4_gender = "Which best describes your gender identity?",
                      Q2_program = "What is your current program at Bloomberg?",
                      Q5_age = "How old are you?",
                      Q6_numberinhousehold = "How many people live in your household, including yourself?",
                      Q37_employed = "If you are a student at Bloomberg, are you currently employed outside of your education program?",
                      Q92_notSPHemployed = "Are you currently employed?",
                      Q93_worksetting = "Which of the following best describes your current work setting?",
                      Q94_dayornight = "Do you work day or night shifts?",
                      Q38_worksetting = "Which of the following best describes your current work setting?",
                      Q39_dayornight = "Do you work day or night shifts?",
                      Q10_hoursofsleeplast5workdays = "On average, how many hours of sleep did you get per night during the following periods of time: during the last 5 workdays?",
                      Q10_hoursofsleeppastweekend = "On average, how many hours of sleep did you get per night during the following periods of time: during the past weekend?",
                      Q9_howoftensleepypastmonth = "How often did you feel sleepy during the day in the past month?",
                      Q61_howoftensleepypasttwoweeks = "How often did you feel sleepy during the day during the past 2 weeks?",
                      Q84_awareofhowtoimprovesleepquality = "Do you know any ways a person can improve their sleep quality?",
                      Q85_waystoimprovesleepquality = "What are some of the ways to improve sleep quality that you know?",
                      Q81_seenorheardfromGNbloombergcampaign = "In the last two-three weeks have you heard, seen, or received any information from the #GoodnightBloomberg campaign led by JHSPH students promoting better sleep?",
                      Q63_recalltoolsfreetect = "Can you recall any specific tools, techniques, or resources from the campaign? Please describe below.",
                      Q96_picture1 = "Were these materials were utilized in our #GoodnightBloomberg campaign? Picture 1",
                      Q96_picture2 = "Were these materials were utilized in our #GoodnightBloomberg campaign? Picture 2",
                      Q96_picture3 = "Were these materials were utilized in our #GoodnightBloomberg campaign? Picture 3",
                      Q96_picture4 = "Were these materials were utilized in our #GoodnightBloomberg campaign? Picture 4",
                      Q96_picture5 = "Were these materials were utilized in our #GoodnightBloomberg campaign? Picture 5",
                      Q96_picture6 = "Were these materials were utilized in our #GoodnightBloomberg campaign? Picture 6",
                      Q96_picture7 = "Were these materials were utilized in our #GoodnightBloomberg campaign? Picture 7",
                      Q96_picture8 = "Were these materials were utilized in our #GoodnightBloomberg campaign? Picture 8",
                      Q95_talkedtoanyone = "Have you talked to anyone about the #GoodnightBloomberg campaign?",
                      Q83_talkedtowho = "Please indicate with whom you talked about #GoodnightBloomberg (check all that apply).",
                      Q82_knowanyonewhoengaged = "Do you know anyone who engaged in any way with the #GoodnightBloomberg campaign about promoting better sleep?",
                      Q69_didyouengagewiththecampaign = "Did you engage in any way with the #GoodnightBloomberg campaign led by JHSPH students during the past 2 weeks?",
                      Q62_howdidyouengage = "Please select which of the following parts of the #GoodnightBloomberg campaign you engaged in:",
                      Q64_whichtechniquedidyoutry = "Which of the following techniques did you try at least once in the last 2 weeks (choose all that apply)?", 
                      Q90_areyouhappywithyoursleepquality_awareofcampaign = "Are you happy with your sleep quality overall currently?", 
                      Q91_areyouhappywithyoursleepquality_notawareofcampaign = "Are you happy with your sleep quality overall currently?", 
                      Q89_ratesleepquality_notawareofcampaign = "Please rate your sleep quality from the following options: In the last two weeks? (on average)",
                      Q67_move30minutes =  "In the last two weeks, how many days did you participate in the following techniques? Move 30 minutes total per day",
                      Q67_breathing = "In the last two weeks, how many days did you participate in the following techniques? Use a breathing exercise",
                      Q67_powerdown = "In the last two weeks, how many days did you participate in the following techniques? Power down your screens (i.e. cell phone, tablet, computer, TV) 1 hour before bed",
                      Q75_moving = "How helpful did you find the following activities for getting better quality sleep in the past 2 weeks? Moving 30 minutes total per day",
                      Q75_breathing = "How helpful did you find the following activities for getting better quality sleep in the past 2 weeks? Using a breathing exercise",
                      Q75_powerdown = "How helpful did you find the following activities for getting better quality sleep in the past 2 weeks? Powering down your screens (i.e. cell phone, tablet, computer, TV) 1 hour before bed",
                      Q68_timing = "Was the timing of the texts/posts convenient for you to adopt the recommended activity? ",
                      Q70_timingoftextsinconvenient = "Please provide information below about why the timing of the texts/posts was inconvenient?", 
                      Q87_idealtime = "What would have been the ideal time to receive the message (EST/EDT)?",
                      Q71_whichchannelmosteducational = "Which channel did you find the most educational?",
                      Q79_moresuccessfuloutcomsuggestions = "I think I would have had a more successful outcome (e.g. better sleep quality) if (choose all that may apply):",
                      Q74_rafflemotivating = "Did you find the raffles motivating for participation in the #GoodnightBloomberg campaign?",
                      Q73_hearabouthow = "How did you hear about the #GoodnightBloomberg campaign?",
                      Q59_canmaintainhealthysleephabits = "Please tell us how confident you feel practicing the following behaviors in order to get better sleep: I can maintain healthy sleep habits.",
                      Q59_cancutoutscreen = "Please tell us how confident you feel practicing the following behaviors in order to get better sleep: I can cut out screen use 1 hour before bed.",
                      Q59_canexercise = "Please tell us how confident you feel practicing the following behaviors in order to get better sleep: I can exercise for 30 minutes total each day.", 
                      Q59_canparticipateinbreathing = "Please tell us how confident you feel practicing the following behaviors in order to get better sleep: I can participate in a breathing exercise during the day or before bed.", 
                      Q44_goodnightsleepisimportant = "Please rate your agreement with the following statements: Getting a good night's sleep is important to me.",
                      Q44_mentalclarity = "Please rate your agreement with the following statements: Having a regular sleep routine improves mental clarity/sharpness.",
                      Q44_feelpositive = "Please rate your agreement with the following statements: I feel positive about the quality of my sleep.",
                      Q44_cuttingoutscreenleadstobettersleep = "Please rate your agreement with the following statements: I think cutting out screen use 1 hour before bed leads to better sleep.",
                      Q44_exercisingleadstobettersleep = "Please rate your agreement with the following statements: I think exercising regularly leads to better sleep.",
                      Q44_breathingexercisesleadstobettersleep = "Please rate your agreement with the following statements: I think participating in breathing exercises during the day or before bed leads to better sleep.",
                      Q44_iwillstopscreens = "Please rate your agreement with the following statements: In the next two weeks, I will stop using screens 1 hour before bed for better sleep.",
                      Q44_iwillexercise = "Please rate your agreement with the following statements: In the next two weeks, I will exercise for at least 30 minutes total each day for better sleep.",
                      Q44_iwillbreathe = "Please rate your agreement with the following statements: In the next two weeks, I will do a daily breathing exercise for better sleep.",
                      Q52_additionalcomments = "Please share any additional comments or feedback you have about the #GoodnightBloomberg sleep campaign below."
                      )
```


```{r Table 1}
attach(sleephygiene)
tab1 <- tableby(~ Q3_role + 
                  Q4_gender +
                  Q5_age +
                  Q6_numberinhousehold +
                  Q37_employed +
                  Q10_hoursofsleeplast5workdays +
                  Q10_hoursofsleeppastweekend +
                  Q9_howoftensleepypastmonth +
                  Q61_howoftensleepypasttwoweeks +
                  Q84_awareofhowtoimprovesleepquality +
                  Q81_seenorheardfromGNbloombergcampaign +
                  #Q63_recalltoolsfreetect +
                  Q96_picture1 +
                  Q96_picture2 +
                  Q96_picture3 +
                  Q96_picture4 +
                  Q96_picture5 +
                  Q96_picture6 +
                  Q96_picture7 +
                  Q96_picture8 +
                  Q95_talkedtoanyone +
                  Q82_knowanyonewhoengaged +
                  Q69_didyouengagewiththecampaign +
                  Q67_move30minutes +
                  Q67_breathing +
                  Q67_powerdown +
                  Q68_timing + 
                  Q79_moresuccessfuloutcomsuggestions +
                  Q59_canmaintainhealthysleephabits +
                  Q59_cancutoutscreen +
                  Q59_canexercise +
                  Q59_canparticipateinbreathing +
                  Q44_goodnightsleepisimportant +
                  Q44_mentalclarity +
                  Q44_feelpositive +
                  Q44_cuttingoutscreenleadstobettersleep +
                  Q44_exercisingleadstobettersleep +
                  Q44_breathingexercisesleadstobettersleep +
                  Q44_iwillstopscreens +
                  Q44_iwillexercise +
                  Q44_iwillbreathe,
                data=sleephygiene, test=TRUE, total=TRUE, 
                numeric.stats=c("medianq1q3"), numeric.test="kwt", cat.test="chisq")
summary(tab1, title='Table 1. Baseline information', pfootnote=TRUE, digits = 2)

#If student
student <- sleephygiene %>% filter(Q3_role %in% c("Part-time student", "Full-time student"))

tab2 <- tableby(~ Q2_program,
                data=student, test=TRUE, total=TRUE, 
                numeric.stats=c("medianq1q3"), numeric.test="kwt", cat.test="chisq")
summary(tab2, title='Table 1. Baseline information', pfootnote=TRUE, digits = 2)

#If employed 
nonbloombergstudentemployed <- sleephygiene %>% filter(Q37_employed == "N/A - I am not a student at Bloomberg")

tab3 <- tableby(~ Q92_notSPHemployed,
                data=nonbloombergstudentemployed, test=TRUE, total=TRUE, 
                numeric.stats=c("medianq1q3"), numeric.test="kwt", cat.test="chisq")
summary(tab3, title='Table 1. Baseline information', pfootnote=TRUE, digits = 2)

#If employed and not bloomberg
employed <- nonbloombergstudentemployed %>% filter(Q92_notSPHemployed == "Yes")

tab4 <- tableby(~ Q93_worksetting,
                data=employed, test=TRUE, total=TRUE, 
                numeric.stats=c("medianq1q3"), numeric.test="kwt", cat.test="chisq")
summary(tab4, title='Table 1. Baseline information', pfootnote=TRUE, digits = 2)

#wfh not bloomberg
#wfhnotbloomberg <- nonbloombergstudentemployed %>% filter(Q93_worksetting == "I work in a location away from my home")

#tab5 <- tableby(~ Q94_dayornight,
#                data=wfhnotbloomberg, test=TRUE, total=TRUE, 
#                numeric.stats=c("medianq1q3"), numeric.test="kwt", cat.test="chisq")
#summary(tab5, title='Table 1. Baseline information', pfootnote=TRUE, digits = 2)

#student at bloomberg
studentemployed <- student %>% filter(Q37_employed == "Yes")

tab6 <- tableby(~ Q38_worksetting,
                data=studentemployed, test=TRUE, total=TRUE, 
                numeric.stats=c("medianq1q3"), numeric.test="kwt", cat.test="chisq")
summary(tab6, title='Table 1. Baseline information', pfootnote=TRUE, digits = 2)

studentemployedlocation <- student %>% filter(Q39_dayornight == "I work in a location away from my home")

#tab7 <- tableby(~ Q39_dayornight,
#                data=studentemployedlocation, test=TRUE, total=TRUE, 
#                numeric.stats=c("medianq1q3"), numeric.test="kwt", cat.test="chisq")
#summary(tab7, title='Table 1. Baseline information', pfootnote=TRUE, digits = 2)


#Aware of how to improve sleep quality
awareofsleepqualityimprovements <- sleephygiene %>% filter(Q84_awareofhowtoimprovesleepquality == "Yes")

tab8 <- tableby(~ Q85_waystoimprovesleepquality,
                data=awareofsleepqualityimprovements, test=TRUE, total=TRUE, 
                numeric.stats=c("medianq1q3"), numeric.test="kwt", cat.test="chisq")
summary(tab8, title='Table 1. Baseline information', pfootnote=TRUE, digits = 2)

#Talked to someone
talkedtosomeone <- sleephygiene %>% filter(Q95_talkedtoanyone == "Yes")

tab9 <- tableby(~ Q83_talkedtowho,
                data=talkedtosomeone, test=TRUE, total=TRUE, 
                numeric.stats=c("medianq1q3"), numeric.test="kwt", cat.test="chisq")
summary(tab9, title='Table 1. Baseline information', pfootnote=TRUE, digits = 2)

#engaged in any way
engagedwiththecampaign <- sleephygiene %>% filter(Q69_didyouengagewiththecampaign == "Yes")

tab10 <- tableby(~ Q62_howdidyouengage +
                   Q64_whichtechniquedidyoutry +
                   Q90_areyouhappywithyoursleepquality_awareofcampaign +
                   Q75_moving +
                   Q75_breathing +
                   Q75_powerdown,
                data=engagedwiththecampaign, test=TRUE, total=TRUE, 
                numeric.stats=c("medianq1q3"), numeric.test="kwt", cat.test="chisq")
summary(tab10, title='Table 1. Baseline information', pfootnote=TRUE, digits = 2)

#did not engagee in any way
noengagementwiththecampagin <- sleephygiene %>% filter(Q69_didyouengagewiththecampaign %in% c("No", "Don't know"))

tab11 <- tableby(~ Q91_areyouhappywithyoursleepquality_notawareofcampaign +
                   Q89_ratesleepquality_notawareofcampaign,
                data=noengagementwiththecampagin, test=TRUE, total=TRUE, 
                numeric.stats=c("medianq1q3"), numeric.test="kwt", cat.test="chisq")
summary(tab11, title='Table 1. Baseline information', pfootnote=TRUE, digits = 2)

#not convenient 
notconvenient <- sleephygiene %>% filter(Q68_timing == "No")

tab12 <- tableby(~ Q70_timingoftextsinconvenient,
                data=noengagementwiththecampagin, test=TRUE, total=TRUE, 
                numeric.stats=c("medianq1q3"), numeric.test="kwt", cat.test="chisq")
summary(tab12, title='Table 1. Baseline information', pfootnote=TRUE, digits = 2)

#tooearlyintheday
tooearlyortoolate <- notconvenient %>% filter(Q70_timingoftextsinconvenient %in% c("Received message too early in the day", "Received message too late in the day"))

tab13 <- tableby(~ Q87_idealtime,
                data=tooearlyortoolate, test=TRUE, total=TRUE, 
                numeric.stats=c("medianq1q3"), numeric.test="kwt", cat.test="chisq")
summary(tab13, title='Table 1. Baseline information', pfootnote=TRUE, digits = 2)

#whichmosteducational
instagramortext <- engagedwiththecampaign %>% filter(Q62_howdidyouengage %in% c("Instagram", "Text message campaign"))

#tab14 <- tableby(~ Q71_whichchannelmosteducational +
#                   Q72,
#                data=instagramortext, test=TRUE, total=TRUE, 
#                numeric.stats=c("medianq1q3"), numeric.test="kwt", cat.test="chisq")
#summary(tab14, title='Table 1. Baseline information', pfootnote=TRUE, digits = 2)

#instagram
instagram <- engagedwiththecampaign %>% filter(Q62_howdidyouengage == "Instagram campaign")

tab15 <- tableby(~ Q74_rafflemotivating,
                data=instagram, test=TRUE, total=TRUE, 
                numeric.stats=c("medianq1q3"), numeric.test="kwt", cat.test="chisq")
summary(tab15, title='Table 1. Baseline information', pfootnote=TRUE, digits = 2)

#seenorheardofthecampiagn
seenordheard <- sleephygiene %>% filter(Q81_seenorheardfromGNbloombergcampaign == "Yes")

tab16 <- tableby(~ Q81_seenorheardfromGNbloombergcampaign,
                data=seenordheard, test=TRUE, total=TRUE, 
                numeric.stats=c("medianq1q3"), numeric.test="kwt", cat.test="chisq")
summary(tab16, title='Table 1. Baseline information', pfootnote=TRUE, digits = 2)
```

```{r}
sleephygiene <- sleephygiene %>% mutate(Engagementyesno = case_when(
  Q69_didyouengagewiththecampaign == "Yes" ~ 1,
  Q69_didyouengagewiththecampaign == "No" ~ 0,
  Q69_didyouengagewiththecampaign == "Don't know" ~ 0,
  is.na(Q69_didyouengagewiththecampaign) ~ NA_real_)) %>%
  mutate(Engagementyesno = factor(Engagementyesno))

tab1 <- tableby(Engagementyesno ~ Q3_role + 
                  Q4_gender +
                  Q5_age +
                  Q6_numberinhousehold +
                  Q37_employed +
                  Q10_hoursofsleeplast5workdays +
                  Q10_hoursofsleeppastweekend +
                  Q9_howoftensleepypastmonth +
                  Q61_howoftensleepypasttwoweeks +
                  Q84_awareofhowtoimprovesleepquality +
                  Q81_seenorheardfromGNbloombergcampaign +
                  Q96_picture1 +
                  Q96_picture2 +
                  Q96_picture3 +
                  Q96_picture4 +
                  Q96_picture5 +
                  Q96_picture6 +
                  Q96_picture7 +
                  Q96_picture8 +
                  Q95_talkedtoanyone +
                  Q82_knowanyonewhoengaged +
                  Q69_didyouengagewiththecampaign +
                  Q67_move30minutes +
                  Q67_breathing +
                  Q67_powerdown +
                  Q68_timing + 
                  Q79_moresuccessfuloutcomsuggestions +
                  Q59_canmaintainhealthysleephabits +
                  Q59_cancutoutscreen +
                  Q59_canexercise +
                  Q59_canparticipateinbreathing +
                  Q44_goodnightsleepisimportant +
                  Q44_mentalclarity +
                  Q44_feelpositive +
                  Q44_cuttingoutscreenleadstobettersleep +
                  Q44_exercisingleadstobettersleep +
                  Q44_breathingexercisesleadstobettersleep +
                  Q44_iwillstopscreens +
                  Q44_iwillexercise +
                  Q44_iwillbreathe,
                data=sleephygiene, test=TRUE, total=TRUE, 
                numeric.stats=c("medianq1q3"), numeric.test="kwt", cat.test="chisq")
summary(tab1, title='Table 1. Baseline information', pfootnote=TRUE, digits = 2)
```

```{r}
sleephygienepre <- readRDS(file="foranalysis.rds")

sleephygienepre <- sleephygienepre %>% 
  mutate(Q5_age = case_when(
    Q5_age >= 18 & Q5_age <= 25 ~ "18-25",
    Q5_age >= 26 & Q5_age <= 34 ~ "26-34",
    Q5_age >= 35 & Q5_age <= 44 ~ "35-44",
    Q5_age >= 45 & Q5_age <= 54 ~ "45-54",
    Q5_age >= 55 & Q5_age < 64 ~ "55-64",
    Q5_age >= 64 & Q5_age <= 75 ~ "64-75",
    Q5_age > 75 ~ "75+",
    is.na(Q5_age) ~ NA_character_
  )) %>% 
  mutate(Q5_age = factor(Q5_age)) %>%
  mutate(post = 0) %>% 
  mutate(
    Q10_hoursofsleeplast5workdays = Q10_workdayhoursofsleep,
    Q10_hoursofsleeppastweekend = Q11_weekendhoursofsleep,
    Q61_howoftensleepypasttwoweeks = Q9_howoftensleepy
  ) %>%
  select(post, Q3_role, Q2_program, Q4_gender, Q5_age, Q6_numberinhousehold, Q10_hoursofsleeplast5workdays, Q10_hoursofsleeppastweekend, Q61_howoftensleepypasttwoweeks) 
  
sleephygienepost <- sleephygiene %>% mutate(post = 1) %>% select(post, Q3_role, Q2_program, Q4_gender, Q5_age, Q6_numberinhousehold, Q10_hoursofsleeplast5workdays, Q10_hoursofsleeppastweekend, Q61_howoftensleepypasttwoweeks) 

sleephygienepreandpost <- rbind(sleephygienepre, sleephygienepost)

sleephygienepreandpost <- sleephygienepreandpost %>% mutate(Q61_smaller = case_when(
  is.na(Q61_howoftensleepypasttwoweeks) ~ NA_character_,
  Q61_howoftensleepypasttwoweeks == "Never" ~ "Never",
  Q61_howoftensleepypasttwoweeks == "Rarely" ~ "Rarely",
  Q61_howoftensleepypasttwoweeks == "Sometimes" ~ "Sometimes",
  Q61_howoftensleepypasttwoweeks == "Very often" | Q61_howoftensleepypasttwoweeks == "Always" ~ "Very often or Always",
)) %>%
  mutate(Q61_smaller = factor(Q61_smaller)) %>%
  mutate(Q2_program = case_when(
  Q2_program == "Post-doctoral student" ~ as.character("Post doctoral student"),
  TRUE ~ as.character(Q2_program)
  )) %>%
  mutate(Q2_program = factor(Q2_program))

tab1 <- tableby(post ~ Q3_role +
                  Q2_program + 
                  Q4_gender + 
                  Q5_age + 
                  Q6_numberinhousehold +
                  Q10_hoursofsleeplast5workdays +
                  Q10_hoursofsleeppastweekend +
                  Q61_smaller,
                data=sleephygienepreandpost, test=TRUE, total=TRUE, 
                numeric.stats=c("medianq1q3"), numeric.test="kwt", cat.test="chisq")
summary(tab1, title='Table 1. Baseline information', pfootnote=TRUE, digits = 2)
```

```{r}
library(sjPlot)
sleephygiene <- sleephygiene %>% mutate(Q69_didyouengagewiththecampaignbinary = case_when(
  Q69_didyouengagewiththecampaign == "No" ~ 0,
  Q69_didyouengagewiththecampaign == "Yes" ~ 1)) %>%
  mutate(Q4_gender_binary = case_when(
    Q4_gender == "Male" ~ 1,
    Q4_gender == "Female" ~ 0,
    TRUE ~ NA_real_
  )) %>%
  mutate(Q4_gender_binary = factor(Q4_gender_binary, labels = c("Female", "Male"))) %>%
  mutate(happywithsleepqualitycombined = case_when(
    Q90_areyouhappywithyoursleepquality_awareofcampaign == "Yes" ~ 1,
    Q90_areyouhappywithyoursleepquality_awareofcampaign == "No" ~ 0,
    Q91_areyouhappywithyoursleepquality_notawareofcampaign == "Yes" ~ 1,
    Q91_areyouhappywithyoursleepquality_notawareofcampaign == "No" ~ 0,
    Q89_ratesleepquality_notawareofcampaign == "Good" ~ 1,
    Q89_ratesleepquality_notawareofcampaign == "Excellent" ~ 1,
    Q89_ratesleepquality_notawareofcampaign == "Poor" ~ 0,
    Q89_ratesleepquality_notawareofcampaign == "Fair" ~ 0,
  )) %>%
  mutate(happywithsleepqualitycombined = factor(happywithsleepqualitycombined)) %>%
  mutate(Q67_1 = case_when(
    is.na(Q67_1) ~ 0,
    TRUE ~ as.numeric(Q67_1)
  )) %>%
  mutate(Q67_2 = case_when(
    is.na(Q67_2) ~ 0,
    TRUE ~ as.numeric(Q67_2)
  )) %>%
  mutate(Q67_3 = case_when(
    is.na(Q67_3) ~ 0,
    TRUE ~ as.numeric(Q67_3)
  )) %>%
  mutate(pointscombinedperdays = Q67_1 + Q67_2 + Q67_3) %>%
  mutate(ratesleepqualitycombined = case_when(
    Q89_ratesleepquality_notawareofcampaign == "Good" ~ 1,
    Q89_ratesleepquality_notawareofcampaign == "Excellent" ~ 1,
    Q89_ratesleepquality_notawareofcampaign == "Poor" ~ 0,
    Q89_ratesleepquality_notawareofcampaign == "Fair" ~ 0,
  )) %>%
  mutate(POINTSFROMPICS1 = case_when(
    Q96_picture2 == "Yes" ~ 1,
    TRUE ~ 0
  )) %>%
  mutate(POINTSFROMPICS2 = case_when(
    Q96_picture4 == "Yes" ~ 1,
    TRUE ~ 0
  )) %>% mutate(POINTSFROMPICS3 = case_when(
    Q96_picture5 == "Yes" ~ 1,
    TRUE ~ 0
  )) %>% mutate(POINTSFROMPICS4 = case_when(
    Q96_picture7 == "Yes" ~ 1,
    TRUE ~ 0
  )) %>% mutate(POINTFROMENGAGEMENT = case_when(
    Q69_didyouengagewiththecampaign == "Yes" ~ 1,
    TRUE ~ 0
    )) %>% mutate(
      POINTSFROMPARTICIPATION = X.MoveMore + X.PowerDown + X.Breathe
    ) %>%
  mutate(TOTALPOINTS = pointscombinedperdays + POINTSFROMPICS1 + POINTSFROMPICS2 + POINTSFROMPICS3 + POINTSFROMPICS4 + POINTFROMENGAGEMENT + POINTSFROMPARTICIPATION) %>% mutate(AGESMALLERCATEGORIES = case_when(
    Q5_age == "18-25" ~ 0,
    Q5_age == "26-34" ~ 0,
    Q5_age == "35-44" ~ 0,
    Q5_age == "45-54" ~ 1,
    Q5_age == "55-64" ~ 1,
    Q5_age == "64-75" ~ 1
  )) %>%
  mutate(POINTSFROMSOCIAL = Instagram.campaign + Text.message.campaign + Word.of.mouth.discussion.with.others) %>% mutate(POINTSFROMSOCIAL = as.numeric((POINTSFROMSOCIAL))) %>%
  mutate(POINTSFROMPARTICIPATION = as.numeric(POINTSFROMPARTICIPATION))
  
#Participating in the campaign
mylogit <- glm(Q69_didyouengagewiththecampaignbinary ~ Q4_gender_binary + Q10_hoursofsleeplast5workdays + Q10_hoursofsleeppastweekend, family = binomial(link = "logit"), data = sleephygiene)
tab_model(mylogit)

#Happy with sleep quality
mylogit <- glm(happywithsleepqualitycombined ~ Q4_gender_binary + Q10_hoursofsleeplast5workdays + Q10_hoursofsleeppastweekend + Q69_didyouengagewiththecampaignbinary, family = binomial(link = "logit"), data = sleephygiene)
tab_model(mylogit)

mylogit <- glm(happywithsleepqualitycombined ~ Q10_hoursofsleeppastweekend + Q4_gender_binary + pointscombinedperdays, family = binomial(link = "logit"), data = sleephygiene)
tab_model(mylogit)
attach(sleephygiene)
mylogit <- glm(happywithsleepqualitycombined ~ TOTALPOINTS + Q10_hoursofsleeplast5workdays + Q3_role + Q4_gender_binary + AGESMALLERCATEGORIES, family = binomial(link = "logit"), data = sleephygiene)
tab_model(mylogit)
```


```{r}
#knowing campaign exists
#ACTION IS THE OUTCOME
#Can you recall images
#texting campaign
#composite outcome HIGH AND LOW EXPOSURE

#HIGH VS LOW EXPOSURE
#LOGISTIC REGRESSION -- BEHAVIOR
#OR LINEAR REGRESSION
#Causal criteria...
```

```{r Define exposure}
sleephygiene <- sleephygiene %>% mutate(TOTALPOINTS_EXCLUDINGDAYSOFPARTICIPATION = POINTSFROMPICS1 + POINTSFROMPICS2 + POINTSFROMPICS3 + POINTSFROMPICS4 + POINTFROMENGAGEMENT + POINTSFROMPARTICIPATION + POINTSFROMSOCIAL) %>%
  mutate(CAMPAIGN_EXPOSURE = case_when(
    is.na(TOTALPOINTS_EXCLUDINGDAYSOFPARTICIPATION) ~ NA_real_,
    TOTALPOINTS_EXCLUDINGDAYSOFPARTICIPATION >= 5 ~ 2,
    TOTALPOINTS_EXCLUDINGDAYSOFPARTICIPATION < 5 & TOTALPOINTS_EXCLUDINGDAYSOFPARTICIPATION > 0 ~ 1,
    TOTALPOINTS_EXCLUDINGDAYSOFPARTICIPATION == 0 ~ 0
  )) %>% mutate(CAMPAIGN_EXPOSURE = factor(CAMPAIGN_EXPOSURE))

quantile(sleephygiene$TOTALPOINTS_EXCLUDINGDAYSOFPARTICIPATION, c(.25, .50,  .75, .90, .99))
```

```{r Self efficacy to motivation}
sleephygiene <- sleephygiene %>% 
  mutate(SELF_EFFICACY_1 = case_when(
    Q59_canmaintainhealthysleephabits == "Extremely confident" ~ 1,
    is.na(Q59_canmaintainhealthysleephabits) ~ NA_real_,
    TRUE ~ 0)) %>%
  mutate(SELF_EFFICACY_2 = case_when(
    Q59_canparticipateinbreathing == "Extremely confident" ~ 1,
    is.na(Q59_canparticipateinbreathing) ~ NA_real_,
    TRUE ~ 0
  )) %>%
  mutate(SELF_EFFICACY_3 = case_when(
    Q59_cancutoutscreen == "Extremeley confident" ~ 1,
    is.na(Q59_cancutoutscreen) ~ NA_real_,
    TRUE ~ 0
  )) %>% 
  mutate(SELF_EFFICACY_4 = case_when(
    Q59_canexercise == "Extremeley confident" ~ 1,
    is.na(Q59_canexercise) ~ NA_real_,
    TRUE ~ 0
  )) %>% mutate(
  SELF_EFFICACY_COMBINED = SELF_EFFICACY_1 + SELF_EFFICACY_2 + SELF_EFFICACY_3 + SELF_EFFICACY_4) %>%
  mutate(
    RESPONSEEFFICACY = case_when(
    Q44_cuttingoutscreenleadstobettersleep == "Strongly agree" ~ 1,
    is.na(Q44_cuttingoutscreenleadstobettersleep) ~ NA_real_,
    Q44_exercisingleadstobettersleep == "Strongly agree" ~ 1,
    is.na(Q44_exercisingleadstobettersleep) ~ NA_real_,
    Q44_breathingexercisesleadstobettersleep == "Strongly agree" ~ 1,
    is.na(Q44_breathingexercisesleadstobettersleep) ~ NA_real_,
    TRUE ~ 0
  )) %>%
  mutate(RESPONSEEFFICACY_1 = case_when(
    Q44_cuttingoutscreenleadstobettersleep == "Strongly agree" ~ 1,
    is.na(Q44_cuttingoutscreenleadstobettersleep) ~ NA_real_,
    TRUE ~ 0)) %>%
  mutate(RESPONSEEFFICACY_2 = case_when(
    Q44_exercisingleadstobettersleep == "Strongly agree" ~ 1,
    is.na(Q44_exercisingleadstobettersleep) ~ NA_real_,
    TRUE ~ 0
  )) %>%
  mutate(RESPONSEEFFICACY_3 = case_when(
    Q44_breathingexercisesleadstobettersleep == "Strongly agree" ~ 1,
    is.na(Q44_breathingexercisesleadstobettersleep) ~ NA_real_,
    TRUE ~ 0
  )) %>% mutate(RESPONSEEFFICACY_COMBINED = RESPONSEEFFICACY_1 + RESPONSEEFFICACY_2 + RESPONSEEFFICACY_3)


mylogit <- glm(RESPONSEEFFICACY ~ SELF_EFFICACY_COMBINED + Q4_gender_binary +Q10_hoursofsleeplast5workdays, family = binomial(link = "logit"), data = sleephygiene)
tab_model(mylogit)


#SELF EFFICACY
mylinear <- glm(SELF_EFFICACY_COMBINED ~ CAMPAIGN_EXPOSURE + Q4_gender_binary +Q10_hoursofsleeplast5workdays + Q3_role, family = "gaussian", data = sleephygiene)
summary(mylinear)

#
mylinear <- glm(pointscombinedperdays ~ SELF_EFFICACY_COMBINED + Q4_gender_binary +Q10_hoursofsleeplast5workdays + Q3_role, family = "gaussian", data = sleephygiene)
summary(mylinear)

```

```{r Response efficacy}
mylinear <- glm(RESPONSEEFFICACY_COMBINED ~ CAMPAIGN_EXPOSURE + Q4_gender_binary +Q10_hoursofsleeplast5workdays + Q3_role, family = "gaussian", data = sleephygiene)
summary(mylinear)

mylinear <- glm(pointscombinedperdays ~ RESPONSEEFFICACY_COMBINED + Q4_gender_binary +Q10_hoursofsleeplast5workdays + Q3_role, family = "gaussian", data = sleephygiene)
summary(mylinear)
```


```{r EXPOSURE to campaign}
quantile(sleephygiene$TOTALPOINTS_EXCLUDINGDAYSOFPARTICIPATION, c(.25, .50,  .75, .90, .99))

#Dependent variable 
mylinear <- glm(pointscombinedperdays ~ CAMPAIGN_EXPOSURE, family = "gaussian", data = sleephygiene)
summary(mylinear)

mylinear <- glm(pointscombinedperdays ~ CAMPAIGN_EXPOSURE + AGESMALLERCATEGORIES + Q4_gender_binary, family = "gaussian", data = sleephygiene)
summary(mylinear)
```


```{r Attitude}
sleephygiene <- sleephygiene %>% mutate(
  ATTITUDE = case_when(
    Q44_goodnightsleepisimportant == "Strongly agree" ~ 1,
    is.na(Q44_goodnightsleepisimportant) ~ NA_real_,
    Q44_mentalclarity == "Strongly agree" ~ 1,
    is.na(Q44_mentalclarity) ~ NA_real_,
    TRUE ~ 0
  )
) %>%
  mutate(ATTITUDE_1 = case_when(
    Q44_goodnightsleepisimportant == "Strongly agree" ~ 1,
    is.na(Q44_goodnightsleepisimportant) ~ NA_real_,
    TRUE ~ 0
  )) %>%
  mutate(ATTITUDE_2 = case_when(
    Q44_mentalclarity == "Strongly agree" ~ 1,
    is.na(Q44_mentalclarity) ~ NA_real_,
    TRUE ~ 0
  )) %>% mutate(ATTITUDE_COMBINED = ATTITUDE_1 + ATTITUDE_2)

mylogit <- glm(RESPON ~ ATTITUDE + Q4_gender_binary +Q10_hoursofsleeplast5workdays, family = binomial(link = "logit"), data = sleephygiene)
tab_model(mylogit)

#univariable
mylogit <- glm(ATTITUDE ~ CAMPAIGN_EXPOSURE + Q4_gender_binary +Q10_hoursofsleeplast5workdays, family = binomial(link = "logit"), data = sleephygiene)
tab_model(mylogit)

mylinear <- glm(ATTITUDE_COMBINED ~ CAMPAIGN_EXPOSURE + AGESMALLERCATEGORIES + Q4_gender_binary + Q10_hoursofsleeplast5workdays, family = "gaussian", data = sleephygiene)
summary(mylinear)

#behavior
mylinear <- glm(pointscombinedperdays ~ ATTITUDE_COMBINED + AGESMALLERCATEGORIES + Q4_gender_binary + Q10_hoursofsleeplast5workdays, family = "gaussian", data = sleephygiene)
summary(mylinear)
```

```{r Emotions}
sleephygiene <- sleephygiene %>% mutate(
  EMOTIONS = case_when(
    Q44_feelpositive == "Strongly agree" ~ 1,
    is.na(Q44_feelpositive) ~ NA_real_,
    TRUE ~ 0
  )
)

mylogit <- glm(RESPONSEEFFICACY ~ EMOTIONS + Q4_gender_binary +Q10_hoursofsleeplast5workdays, family = binomial(link = "logit"), data = sleephygiene)
tab_model(mylogit)

#
mylogit <- glm(EMOTIONS ~ CAMPAIGN_EXPOSURE + AGESMALLERCATEGORIES + Q10_hoursofsleeplast5workdays +Q4_gender_binary, family = binomial(link = "logit"), data = sleephygiene)
tab_model(mylogit)

mylinear <- glm(pointscombinedperdays ~ EMOTIONS + AGESMALLERCATEGORIES + Q10_hoursofsleeplast5workdays +Q4_gender_binary, family = "gaussian", data = sleephygiene)
summary(mylinear)
```

```{r Motivation to intention to perform}
#sleephygiene <- sleephygiene %>% mutate(
#  INTENTION = case_when(
#   Q44_iwillstopscreens == "Strongly agree" ~ 1,
#    is.na(Q44_iwillstopscreens) ~ NA_real_,
#    Q44_iwillbreathe == "Strongly agree" ~ 1,
#    is.na(Q44_iwillbreathe) ~ NA_real_,
#    Q44_iwillexercise == "Strongly agree" ~ 1,
#    is.na(Q44_iwillexercise) ~ NA_real_,
#    TRUE ~ 0
#  )
#)

#mylogit <- glm(INTENTION ~ MOTIVATION + Q4_gender_binary +Q10_hoursofsleeplast5workdays, family = binomial(link = "logit"), data = sleephygiene)
#tab_model(mylogit)
```

```{r Behavior}
quantile(sleephygiene$pointscombinedperdays, c(.25, .50,  .75, .90, .99))

sleephygiene <- sleephygiene %>% mutate(
  UPPERPERCENTILEexposure = case_when(
    pointscombinedperdays >= 15 ~ 1,
    is.na(pointscombinedperdays) ~ NA_real_,
    TRUE ~ 0
  )
) %>%
  mutate(
  UPPERPERCENTILEexposure_categories = case_when(
    pointscombinedperdays >= 15 ~ 2,
    pointscombinedperdays < 15  ~ 1,
    is.na(pointscombinedperdays) ~ NA_real_,
    TRUE ~ 0
  )
)

mylogit <- glm(UPPERPERCENTILEexposure ~ INTENTION + Q4_gender_binary +Q10_hoursofsleeplast5workdays, family = binomial(link = "logit"), data = sleephygiene)
tab_model(mylogit)

#
mylinear <- glm(pointscombinedperdays ~ CAMPAIGN_EXPOSURE + AGESMALLERCATEGORIES + Q4_gender_binary + Q10_hoursofsleeplast5workdays, family = "gaussian", data = sleephygiene)
summary(mylinear)
```

```{r Exposure}
mylogit <- glm(happywithsleepqualitycombined ~ UPPERPERCENTILEexposure_categories + Q4_gender_binary +Q10_hoursofsleeplast5workdays, family = binomial(link = "logit"), data = sleephygiene)
tab_model(mylogit)
```

```{r}
mylogit <- glm(happywithsleepqualitycombined ~ TOTALPOINTS + Q10_hoursofsleeplast5workdays + Q3_role + Q4_gender_binary + AGESMALLERCATEGORIES, family = binomial(link = "logit"), data = sleephygiene)
tab_model(mylogit)

mylogit <- glm(happywithsleepqualitycombined ~  pointscombinedperdays + Q10_hoursofsleeplast5workdays + Q3_role + Q4_gender_binary + AGESMALLERCATEGORIES, family = binomial(link = "logit"), data = sleephygiene)
tab_model(mylogit)

mylogit <- glm(happywithsleepqualitycombined ~  Q67_1 + Q67_2 + Q67_3 + Q10_hoursofsleeplast5workdays + Q3_role + Q4_gender_binary + AGESMALLERCATEGORIES, family = binomial(link = "logit"), data = sleephygiene)
tab_model(mylogit)

```

```{r}
#FREQUENCY OF PROMOTED BEHAVIOR

#look at if the people that participated in the campaign hade a higher degree of exposure

#exposure identify the pictures
#or did something with the messaging 
#social media content
#indicate that they are processing the message 


#GIVE PEOPLE A POINT FOR EVERY SOURCE TOGETHER IN AN EXPOSURE MEASURE
#PICTURES, OTHER OPPORTUNITYIES
#TALKES TO ANYONE

#POEPLE WITH HIGEHR LEVEL OF EXPSOURE WHO RECALLED MORE SOURCES SHOULD REPORT MORE BEHAVIORS

#TAKE OUT INTENTION ---- UNCLEAR WHETHER THAT IS (USED IF YOU DONT HAVE A GOOD BEHAVIOR)

#LEVEL OF EXPOSURE BIVARIATE WAY FIRST WANT TO SEE WHETHER EXPOSURE IS ASSOCIATED WITH THE TIMES YOU ATTEMPTED THE BEHAVIOR
#THEN YOU WANT TO TEST WHETHER EXPOSURE IS ASSOCIATED WITH SELF EFFICACY AND EMOTIONS

#CUE TO ACTION DROP

#SELF EFFIACY ATTITUE EMOTIONS (PREDICTORS) -- BIVARIATE TESTS OF THE RELATIONSHIP BETWEEN EXPOSURE (HIGH LOW) AND SELF EFFICACY, SELF EFIACY, SELF-EFFICACY 


#1#DEMOGRAPHICS --> BEHAVIOR, THEN ADD SELF EFFIACCY< ATTITUDE, SEE IF 2DEMOGRAPHIC VARIABLES STILL SIGNIFICANT THAT TEL
#3. EXPSOURE ON SELF EFFICACY, EXPOSURE ON ATTITUDE, EXPOSURE on EMOTIONS
#4 BEHAVIOR PREDICTED BY DEMOGRAPHICS< PYSCHOCSOCIAL ADN EXPOSURE


#CORERLATE NUMBER OF BEHAVIORS AND SUBJECTIVE QUALITY OF SLEEP
#THEN ADD DEMOGRAPHIOCS
#THEN ADD PSYCHOSOCIAL
#THEN ADD EXPOSURE 

#MOTIVATION -= RESPONSE EFFICACY THAT IS A BELIEF IN THE BEHAVIOR IN THAT YOU THINK THEY ARE 
#THOSE CAN BE SELF - EFFIACCYCA
#SEPARATE BOX FOR RESPONSE EFFICACY NOT MOTIVATION

#DONT NEED INTENTION
```

```{r}
sleephygiene <- sleephygiene %>% mutate(
  CAMPAIGN_EXPOSURE_ANY = case_when(
    CAMPAIGN_EXPOSURE == "1" ~ 1,
    CAMPAIGN_EXPOSURE == "2" ~ 1,
    CAMPAIGN_EXPOSURE == "0" ~ 0,
    is.na(CAMPAIGN_EXPOSURE) ~ NA_real_
  )
) %>%
  mutate(CAMPAIGN_EXPOSURE = factor(CAMPAIGN_EXPOSURE, labels = c("None", "Low", "High")))

myColors <- ifelse(levels(sleephygiene$CAMPAIGN_EXPOSURE)=="None", rgb(0.1,0.1,0.7,0.5) , 
              ifelse(levels(sleephygiene$CAMPAIGN_EXPOSURE)=="Low", rgb(0.8,0.1,0.3,0.6),
              ifelse(levels(sleephygiene$CAMPAIGN_EXPOSURE)=="High", rgb(0.8,0.1,0.7,0.3),
              "grey90" )))

boxplot(sleephygiene$pointscombinedperdays ~ sleephygiene$CAMPAIGN_EXPOSURE, 
    col=myColors , 
    ylab="Number of days participating in any behavior" , xlab="Any campaign exposure")


quantile(sleephygiene$pointscombinedperdays, c(.25, .50,  .75, .90, .99))

sleephygiene <- sleephygiene %>% mutate(
  THREECATEGORIES = case_when(
    pointscombinedperdays >= 15 ~ 2,
    pointscombinedperdays < 15 & pointscombinedperdays >= 5 ~ 1,
    pointscombinedperdays < 5 ~ 0,
    is.na(pointscombinedperdays) ~ NA_real_
  )
)

tab1 <- tableby(CAMPAIGN_EXPOSURE ~ pointscombinedperdays +
                  as.factor(THREECATEGORIES),
                data=sleephygiene, test=TRUE, total=TRUE, 
                numeric.stats=c("medianq1q3"), numeric.test="kwt", cat.test="chisq")
summary(tab1, title='Table 1. Baseline information', pfootnote=TRUE, digits = 2)






```

```{r}
mylinear <- glm(pointscombinedperdays ~ CAMPAIGN_EXPOSURE +RESPONSEEFFICACY_COMBINED + SELF_EFFICACY_COMBINED + ATTITUDE_COMBINED + EMOTIONS + Q4_gender_binary +Q10_hoursofsleeplast5workdays + Q3_role, family = "gaussian", data = sleephygiene)
summary(mylinear)
```

**MAY 12**
```{r EXPOSURE INDEPENDENT}
#SELF EFFICACY
mylinear <- glm(SELF_EFFICACY_COMBINED ~ CAMPAIGN_EXPOSURE + Q4_gender_binary +Q10_hoursofsleeplast5workdays + Q3_role, family = "gaussian", data = sleephygiene)
summary(mylinear)

mylinear <- glm(SELF_EFFICACY_COMBINED ~ TOTALPOINTS_EXCLUDINGDAYSOFPARTICIPATION + Q4_gender_binary +Q10_hoursofsleeplast5workdays + Q3_role, family = "gaussian", data = sleephygiene)
summary(mylinear)

#bivariate
mylinear <- glm(SELF_EFFICACY_COMBINED ~ CAMPAIGN_EXPOSURE, family = "gaussian", data = sleephygiene)
summary(mylinear)

#Attitude
mylinear <- glm(ATTITUDE_COMBINED ~ CAMPAIGN_EXPOSURE + AGESMALLERCATEGORIES + Q4_gender_binary + Q10_hoursofsleeplast5workdays, family = "gaussian", data = sleephygiene)
summary(mylinear)

mylinear <- glm(ATTITUDE_COMBINED ~ TOTALPOINTS_EXCLUDINGDAYSOFPARTICIPATION + AGESMALLERCATEGORIES + Q4_gender_binary + Q10_hoursofsleeplast5workdays, family = "gaussian", data = sleephygiene)
summary(mylinear)

#bivariate
mylinear <- glm(ATTITUDE_COMBINED ~ CAMPAIGN_EXPOSURE, family = "gaussian", data = sleephygiene)
summary(mylinear)

#Emotions
mylogit <- glm(EMOTIONS ~ CAMPAIGN_EXPOSURE + AGESMALLERCATEGORIES + Q10_hoursofsleeplast5workdays +Q4_gender_binary, family = binomial(link = "logit"), data = sleephygiene)
tab_model(mylogit)

mylogit <- glm(EMOTIONS ~ TOTALPOINTS_EXCLUDINGDAYSOFPARTICIPATION + AGESMALLERCATEGORIES + Q10_hoursofsleeplast5workdays +Q4_gender_binary, family = binomial(link = "logit"), data = sleephygiene)
tab_model(mylogit)

mylogit <- glm(EMOTIONS ~ CAMPAIGN_EXPOSURE, family = binomial(link = "logit"), data = sleephygiene)
tab_model(mylogit)

#Response efficacy
mylinear <- glm(RESPONSEEFFICACY_COMBINED ~ CAMPAIGN_EXPOSURE + Q4_gender_binary +Q10_hoursofsleeplast5workdays + Q3_role, family = "gaussian", data = sleephygiene)
summary(mylinear)

mylinear <- glm(RESPONSEEFFICACY_COMBINED ~ TOTALPOINTS_EXCLUDINGDAYSOFPARTICIPATION + Q4_gender_binary +Q10_hoursofsleeplast5workdays + Q3_role, family = "gaussian", data = sleephygiene)
summary(mylinear)

mylinear <- glm(RESPONSEEFFICACY_COMBINED ~ CAMPAIGN_EXPOSURE, family = "gaussian", data = sleephygiene)
summary(mylinear)

#Behavior 
mylinear <- glm(pointscombinedperdays ~ CAMPAIGN_EXPOSURE + AGESMALLERCATEGORIES + Q4_gender_binary, family = "gaussian", data = sleephygiene)
summary(mylinear)

mylinear <- glm(pointscombinedperdays ~ TOTALPOINTS_EXCLUDINGDAYSOFPARTICIPATION + AGESMALLERCATEGORIES + Q4_gender_binary, family = "gaussian", data = sleephygiene)
summary(mylinear)

mylinear <- glm(pointscombinedperdays ~ CAMPAIGN_EXPOSURE, family = "gaussian", data = sleephygiene)
summary(mylinear)
```

```{r}
#SELF EFFICACY
mylinear <- glm(pointscombinedperdays ~ SELF_EFFICACY_COMBINED + Q4_gender_binary +Q10_hoursofsleeplast5workdays + Q3_role, family = "gaussian", data = sleephygiene)
summary(mylinear)

#bivariate
mylinear <- glm(pointscombinedperdays ~ SELF_EFFICACY_COMBINED, family = "gaussian", data = sleephygiene)
summary(mylinear)

#Attitude
mylinear <- glm(pointscombinedperdays ~ ATTITUDE_COMBINED + AGESMALLERCATEGORIES + Q4_gender_binary + Q10_hoursofsleeplast5workdays, family = "gaussian", data = sleephygiene)
summary(mylinear)

#bivariate
mylinear <- glm(pointscombinedperdays ~ ATTITUDE_COMBINED, family = "gaussian", data = sleephygiene)
summary(mylinear)

#Emotions
mylinear <- glm(pointscombinedperdays ~ EMOTIONS + AGESMALLERCATEGORIES + Q10_hoursofsleeplast5workdays +Q4_gender_binary, family = "gaussian", data = sleephygiene)
summary(mylinear)

#bivariate
mylinear <- glm(pointscombinedperdays ~ EMOTIONS, family = "gaussian", data = sleephygiene)
summary(mylinear)

#Response efficacy
mylinear <- glm(pointscombinedperdays ~ RESPONSEEFFICACY_COMBINED + Q4_gender_binary +Q10_hoursofsleeplast5workdays + Q3_role, family = "gaussian", data = sleephygiene)
summary(mylinear)

#bivariate
mylinear <- glm(pointscombinedperdays ~ RESPONSEEFFICACY_COMBINED, family = "gaussian", data = sleephygiene)
summary(mylinear)

#Exposure
mylinear <- glm(pointscombinedperdays ~ CAMPAIGN_EXPOSURE + AGESMALLERCATEGORIES + Q4_gender_binary, family = "gaussian", data = sleephygiene)
summary(mylinear)

mylinear <- glm(pointscombinedperdays ~ TOTALPOINTS_EXCLUDINGDAYSOFPARTICIPATION + AGESMALLERCATEGORIES + Q4_gender_binary, family = "gaussian", data = sleephygiene)
summary(mylinear)

#bivariate
mylinear <- glm(pointscombinedperdays ~ CAMPAIGN_EXPOSURE, family = "gaussian", data = sleephygiene)
summary(mylinear)
```

```{r}
sleephygiene <- sleephygiene %>% 
  mutate(HIGHBEHAVIOR = case_when(
    pointscombinedperdays >= 15 ~ 1,
    is.na(pointscombinedperdays) ~ NA_real_,
    TRUE ~ 0
  )
)

mylinear <- glm(pointscombinedperdays ~ TOTALPOINTS_EXCLUDINGDAYSOFPARTICIPATION +RESPONSEEFFICACY_COMBINED + SELF_EFFICACY_COMBINED + ATTITUDE_COMBINED + EMOTIONS + Q4_gender_binary +Q10_hoursofsleeplast5workdays + Q3_role, family = "gaussian", data = sleephygiene)
summary(mylinear)


mylogit <- glm(HIGHBEHAVIOR ~ TOTALPOINTS_EXCLUDINGDAYSOFPARTICIPATION +RESPONSEEFFICACY_COMBINED + SELF_EFFICACY_COMBINED + ATTITUDE_COMBINED + EMOTIONS + Q4_gender_binary +Q10_hoursofsleeplast5workdays + Q3_role, family = binomial(link = "logit"), data = sleephygiene)
tab_model(mylogit)
```








